### ISSUE TITLE
Cannot build grammar containing backtick as token

### ISSUE THREAD

**Issue by houlahaj** [goccmack/gogll#2] opened 2020-06-15 13:32 UTC
It seems I'm unable to define a token to be the backtick `.

E.g. consider the `g1.md` grammar:
```
package "g1"

Exp : Exp Op Exp
    | id
    ;

Op : "&" | "|" ;

id : letter <letter | number> ;
```

If I were to extend `id` like so:
```
id : letter <letter | number | '-'> ;
```
all would be handled just fine, but if I were to extend it like so:
```
id : letter <letter | number | '`'> ;
```
then `gogll` would no longer be able to build a parser from it:
```
Parse Errors:
Parse Error: LexAlternates : RegExp | ∙LexAlternates  I[24]=Error (388,391) '`  at line 26 col 32
Expected one of: [.,[,letter,{,(,any,char_lit,lowcase,not,number,upcase,<]
Parse Error: RegExp : LexSymbol ∙RegExp  I[23]=| (386,387) | at line 26 col 30
Expected one of: [any,char_lit,lowcase,number,{,not,upcase,(,.,<,[,letter]
Parse Error: LexAlternates : ∙RegExp  I[23]=| (386,387) | at line 26 col 30
Expected one of: [),>,],}]
Parse Error: RegExp : LexSymbol ∙RegExp  I[21]=| (377,378) | at line 26 col 21
Expected one of: [not,upcase,(,.,<,[,letter,any,char_lit,lowcase,number,{]
Parse Error: LexAlternates : ∙RegExp  I[21]=| (377,378) | at line 26 col 21
Expected one of: [),>,],}]
Parse Error: RegExp : ∙LexSymbol  I[19]=< (369,370) < at line 26 col 13
Expected one of: [>,],|,},),;]
Parse Error: Rules : ∙Rule  I[16]=tokid (357,359) id at line 26 col 1
Expected one of: [EOF]
```

**Comment by goccmack** [comment] 2020-06-15 15:30
@houlahaj 
Thanks James. The problem is fixed in v3.1.5

**Closed by goccmack** 2020-06-15 15:30 UTC
